version: "3.3"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: ./docker
      dockerfile: Dockerfile
    image: crawler-app
    container_name: crawler-webapp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - crawlernetwork
  nginx:
    image: nginx:1.19-alpine
    container_name: crawler-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - crawlernetwork
networks:
  crawlernetwork:
    driver: bridge
